### ISSUE TITLE
Cooldown issue

### ISSUE THREAD

**Issue by AggerTV** [Govindass/Skooldown#1]
Skooldown version: 1.2.0
Skript version: 2.5.3
Server version: Tuinity 1.16.5

Issue:
`command /feed:
	trigger:
		send "test"
		if cooldown "test" isn't over:
			set {_cd} to cooldown "test"
			send "Expire in %{_cd}%"
		else:
			create cooldown "test" for 10 seconds
			send "Worked!"`

{_cd} will always return as "Expire in 0 seconds" even though the cooldown is not 0 seconds until next usage

**Comment by Govindass** [comment]
the code is wrongly formatted

**Comment by Govindass** [comment]
also could you provide a list of skript addons? I think it could be a conflict, because I have my whole network based on Skooldown with no issue

**Comment by AggerTV** [comment]
> the code is wrongly formatted

it's the code you gave me on the spigot thread


> also could you provide a list of skript addons? I think it could be a conflict, because I have my whole network based on Skooldown with no issue

`Installed Skript Addons:
- skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders)
- DiSky v1.8 (https://disky.itsthesky.info/)
- skript-yaml v1.3.2
- skUtilities v0.9.2 (https://tim740.github.io/)
- skript-reflect v2.2.1 (https://github.com/TPGamesNL/skript-reflect)
- skRayFall v1.9.23 (https://sk.rayfall.net/)
- Skooldown v1.2.0
- TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe)
- SharpSK v1.6.3
- WolvSK v1.7.2`

**Comment by Govindass** [comment]
delete WolvSK, it is incompatible with Skooldown due to providing cooldowns too

**Comment by Govindass** [comment]
or you could disable cooldowns in WolvSK config, if it has such option

**Comment by AggerTV** [comment]
Yes, it works now without WolvSK
