### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by AggerTV** [Govindass/Skooldown#2]
My suggestion is, have the time format be translatable. Very simple, I know, but a very usefull feature nonetheless.

**Comment by Govindass** [comment]
you can already do this, open Skript.jar file, in it you can find translation files

**Comment by AggerTV** [comment]
Would you happen to know what the location of the file is? 
If it's the english.lang file, then for some reason the JD decompiler won't open it

**Comment by Govindass** [comment]
you do not need decompiler, just open jar with program like WinRAR and then open .lang with program like Notepad
